apiVersion: v1
kind: Service
metadata:
  namespace: login
  labels:
    app: login
  name: login
spec:
  ports:
  
    - protocol: TCP
      port: 9999
      targetPort: 9999
   
   
  selector:
    app: login
  type: ClusterIP
